#! /bin/sh

#If refresing BSPWM, remove all previous rules to prevent doubling up
bspc rule -r "*"

#Startup stuff
pgrep -x sxhkd > /dev/null || sxhkd &
dunst &
sxhkd &
picom &
/home/dacker/.local/bin/polybar-bspwm &
clipmenud &
volumeicon &
nm-applet &

#Monitor setup
bspc monitor -d I II III IV V VI VII 
xrandr -s 1920x1080 &
feh --bg-fill /home/dacker/.config/wallpaper/wallpaper.jpg &

#Cursor setup
xsetroot -cursor_name left_ptr &

#Config border and gap
bspc config border_width            4
bspc config window_gap              5
#bspc config top_padding             20 #Add value according to bar height

#Config else
bspc config split_ratio             0.50
bspc config borderless_monocle      true
bspc config single_monocle          false
bspc config focus_follows_pointer   true
bspc config gapless_monocle         true

#Colors 
bspc config focused_border_color   "#711c91"
bspc config normal_border_color    "#1a1032"
bspc config active_border_color    "#0abdc6"
bspc config presel_feedback_color  "#fdee00"
bspc config urgent_border_color    "#cc2885"

#Rules for windows
bspc rule -a EXAMPLE desktop='^8' state=floating follow=on
bspc rule -a Screenkey manage=off
